name: "Digital Lifeline"
version: "1.0.4"
slug: "digital_lifeline"
description: "Installeert de Digital Lifeline integratie. Na installatie kun je personen beheren en notificaties versturen via Home Assistant."
url: "https://github.com/dreamfoxmedia/digital-lifeline-ha"
arch:
  - aarch64
  - amd64
startup: application
boot: manual
map:
  - config:rw
